// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_push_notification.proto

package com.akaxin.proto.platform;

public final class ApiPushNotificationProto {
  private ApiPushNotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiPushNotificationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPushNotificationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .core.MsgType push_type = 1;</code>
     */
    int getPushTypeValue();
    /**
     * <code>optional .core.MsgType push_type = 1;</code>
     */
    com.akaxin.proto.core.CoreProto.MsgType getPushType();

    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    boolean hasNotification();
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    com.akaxin.proto.core.PushProto.Notification getNotification();
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    com.akaxin.proto.core.PushProto.NotificationOrBuilder getNotificationOrBuilder();
  }
  /**
   * Protobuf type {@code platform.ApiPushNotificationRequest}
   */
  public  static final class ApiPushNotificationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPushNotificationRequest)
      ApiPushNotificationRequestOrBuilder {
    // Use ApiPushNotificationRequest.newBuilder() to construct.
    private ApiPushNotificationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPushNotificationRequest() {
      pushType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiPushNotificationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              pushType_ = rawValue;
              break;
            }
            case 18: {
              com.akaxin.proto.core.PushProto.Notification.Builder subBuilder = null;
              if (notification_ != null) {
                subBuilder = notification_.toBuilder();
              }
              notification_ = input.readMessage(com.akaxin.proto.core.PushProto.Notification.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notification_);
                notification_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiPushNotificationProto.internal_static_platform_ApiPushNotificationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiPushNotificationProto.internal_static_platform_ApiPushNotificationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.class, com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.Builder.class);
    }

    public static final int PUSH_TYPE_FIELD_NUMBER = 1;
    private int pushType_;
    /**
     * <code>optional .core.MsgType push_type = 1;</code>
     */
    public int getPushTypeValue() {
      return pushType_;
    }
    /**
     * <code>optional .core.MsgType push_type = 1;</code>
     */
    public com.akaxin.proto.core.CoreProto.MsgType getPushType() {
      com.akaxin.proto.core.CoreProto.MsgType result = com.akaxin.proto.core.CoreProto.MsgType.valueOf(pushType_);
      return result == null ? com.akaxin.proto.core.CoreProto.MsgType.UNRECOGNIZED : result;
    }

    public static final int NOTIFICATION_FIELD_NUMBER = 2;
    private com.akaxin.proto.core.PushProto.Notification notification_;
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    public boolean hasNotification() {
      return notification_ != null;
    }
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    public com.akaxin.proto.core.PushProto.Notification getNotification() {
      return notification_ == null ? com.akaxin.proto.core.PushProto.Notification.getDefaultInstance() : notification_;
    }
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>optional .core.Notification notification = 2;</code>
     */
    public com.akaxin.proto.core.PushProto.NotificationOrBuilder getNotificationOrBuilder() {
      return getNotification();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pushType_ != com.akaxin.proto.core.CoreProto.MsgType.NOTICE.getNumber()) {
        output.writeEnum(1, pushType_);
      }
      if (notification_ != null) {
        output.writeMessage(2, getNotification());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pushType_ != com.akaxin.proto.core.CoreProto.MsgType.NOTICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, pushType_);
      }
      if (notification_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNotification());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest other = (com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest) obj;

      boolean result = true;
      result = result && pushType_ == other.pushType_;
      result = result && (hasNotification() == other.hasNotification());
      if (hasNotification()) {
        result = result && getNotification()
            .equals(other.getNotification());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PUSH_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + pushType_;
      if (hasNotification()) {
        hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getNotification().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPushNotificationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPushNotificationRequest)
        com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiPushNotificationProto.internal_static_platform_ApiPushNotificationRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiPushNotificationProto.internal_static_platform_ApiPushNotificationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.class, com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pushType_ = 0;

        if (notificationBuilder_ == null) {
          notification_ = null;
        } else {
          notification_ = null;
          notificationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiPushNotificationProto.internal_static_platform_ApiPushNotificationRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest build() {
        com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest buildPartial() {
        com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest result = new com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest(this);
        result.pushType_ = pushType_;
        if (notificationBuilder_ == null) {
          result.notification_ = notification_;
        } else {
          result.notification_ = notificationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest other) {
        if (other == com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest.getDefaultInstance()) return this;
        if (other.pushType_ != 0) {
          setPushTypeValue(other.getPushTypeValue());
        }
        if (other.hasNotification()) {
          mergeNotification(other.getNotification());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pushType_ = 0;
      /**
       * <code>optional .core.MsgType push_type = 1;</code>
       */
      public int getPushTypeValue() {
        return pushType_;
      }
      /**
       * <code>optional .core.MsgType push_type = 1;</code>
       */
      public Builder setPushTypeValue(int value) {
        pushType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.MsgType push_type = 1;</code>
       */
      public com.akaxin.proto.core.CoreProto.MsgType getPushType() {
        com.akaxin.proto.core.CoreProto.MsgType result = com.akaxin.proto.core.CoreProto.MsgType.valueOf(pushType_);
        return result == null ? com.akaxin.proto.core.CoreProto.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .core.MsgType push_type = 1;</code>
       */
      public Builder setPushType(com.akaxin.proto.core.CoreProto.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        pushType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.MsgType push_type = 1;</code>
       */
      public Builder clearPushType() {
        
        pushType_ = 0;
        onChanged();
        return this;
      }

      private com.akaxin.proto.core.PushProto.Notification notification_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.proto.core.PushProto.Notification, com.akaxin.proto.core.PushProto.Notification.Builder, com.akaxin.proto.core.PushProto.NotificationOrBuilder> notificationBuilder_;
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public boolean hasNotification() {
        return notificationBuilder_ != null || notification_ != null;
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public com.akaxin.proto.core.PushProto.Notification getNotification() {
        if (notificationBuilder_ == null) {
          return notification_ == null ? com.akaxin.proto.core.PushProto.Notification.getDefaultInstance() : notification_;
        } else {
          return notificationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public Builder setNotification(com.akaxin.proto.core.PushProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notification_ = value;
          onChanged();
        } else {
          notificationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public Builder setNotification(
          com.akaxin.proto.core.PushProto.Notification.Builder builderForValue) {
        if (notificationBuilder_ == null) {
          notification_ = builderForValue.build();
          onChanged();
        } else {
          notificationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public Builder mergeNotification(com.akaxin.proto.core.PushProto.Notification value) {
        if (notificationBuilder_ == null) {
          if (notification_ != null) {
            notification_ =
              com.akaxin.proto.core.PushProto.Notification.newBuilder(notification_).mergeFrom(value).buildPartial();
          } else {
            notification_ = value;
          }
          onChanged();
        } else {
          notificationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public Builder clearNotification() {
        if (notificationBuilder_ == null) {
          notification_ = null;
          onChanged();
        } else {
          notification_ = null;
          notificationBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public com.akaxin.proto.core.PushProto.Notification.Builder getNotificationBuilder() {
        
        onChanged();
        return getNotificationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      public com.akaxin.proto.core.PushProto.NotificationOrBuilder getNotificationOrBuilder() {
        if (notificationBuilder_ != null) {
          return notificationBuilder_.getMessageOrBuilder();
        } else {
          return notification_ == null ?
              com.akaxin.proto.core.PushProto.Notification.getDefaultInstance() : notification_;
        }
      }
      /**
       * <pre>
       *通知消息
       * </pre>
       *
       * <code>optional .core.Notification notification = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.proto.core.PushProto.Notification, com.akaxin.proto.core.PushProto.Notification.Builder, com.akaxin.proto.core.PushProto.NotificationOrBuilder> 
          getNotificationFieldBuilder() {
        if (notificationBuilder_ == null) {
          notificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.akaxin.proto.core.PushProto.Notification, com.akaxin.proto.core.PushProto.Notification.Builder, com.akaxin.proto.core.PushProto.NotificationOrBuilder>(
                  getNotification(),
                  getParentForChildren(),
                  isClean());
          notification_ = null;
        }
        return notificationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPushNotificationRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPushNotificationRequest)
    private static final com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest();
    }

    public static com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPushNotificationRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiPushNotificationRequest>() {
      public ApiPushNotificationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPushNotificationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPushNotificationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPushNotificationRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiPushNotificationProto.ApiPushNotificationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPushNotificationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPushNotificationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$platform/api_push_notification.proto\022\010" +
      "platform\032\017core/core.proto\032\017core/push.pro" +
      "to\"h\n\032ApiPushNotificationRequest\022 \n\tpush" +
      "_type\030\001 \001(\0162\r.core.MsgType\022(\n\014notificati" +
      "on\030\002 \001(\0132\022.core.Notification2f\n\032ApiPushN" +
      "otificationService\022H\n\014notification\022$.pla" +
      "tform.ApiPushNotificationRequest\032\022.core." +
      "NoneResponseB5\n\031com.akaxin.proto.platfor" +
      "mB\030ApiPushNotificationProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akaxin.proto.core.CoreProto.getDescriptor(),
          com.akaxin.proto.core.PushProto.getDescriptor(),
        }, assigner);
    internal_static_platform_ApiPushNotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiPushNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPushNotificationRequest_descriptor,
        new java.lang.String[] { "PushType", "Notification", });
    com.akaxin.proto.core.CoreProto.getDescriptor();
    com.akaxin.proto.core.PushProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
