// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_friend_applyResult.proto

package com.akaxin.proto.site;

public final class ApiFriendApplyResultProto {
  private ApiFriendApplyResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiFriendApplyResultRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiFriendApplyResultRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送好友申请的用户
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    java.lang.String getSiteFriendId();
    /**
     * <pre>
     *发送好友申请的用户
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteFriendIdBytes();

    /**
     * <pre>
     *当前用户处理好友申请的结果
     * </pre>
     *
     * <code>optional bool apply_result = 2;</code>
     */
    boolean getApplyResult();
  }
  /**
   * Protobuf type {@code site.ApiFriendApplyResultRequest}
   */
  public  static final class ApiFriendApplyResultRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiFriendApplyResultRequest)
      ApiFriendApplyResultRequestOrBuilder {
    // Use ApiFriendApplyResultRequest.newBuilder() to construct.
    private ApiFriendApplyResultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiFriendApplyResultRequest() {
      siteFriendId_ = "";
      applyResult_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiFriendApplyResultRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteFriendId_ = s;
              break;
            }
            case 16: {

              applyResult_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.class, com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.Builder.class);
    }

    public static final int SITE_FRIEND_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteFriendId_;
    /**
     * <pre>
     *发送好友申请的用户
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    public java.lang.String getSiteFriendId() {
      java.lang.Object ref = siteFriendId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteFriendId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送好友申请的用户
     * </pre>
     *
     * <code>optional string site_friend_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteFriendIdBytes() {
      java.lang.Object ref = siteFriendId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteFriendId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLY_RESULT_FIELD_NUMBER = 2;
    private boolean applyResult_;
    /**
     * <pre>
     *当前用户处理好友申请的结果
     * </pre>
     *
     * <code>optional bool apply_result = 2;</code>
     */
    public boolean getApplyResult() {
      return applyResult_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteFriendIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteFriendId_);
      }
      if (applyResult_ != false) {
        output.writeBool(2, applyResult_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteFriendIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteFriendId_);
      }
      if (applyResult_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, applyResult_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest other = (com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest) obj;

      boolean result = true;
      result = result && getSiteFriendId()
          .equals(other.getSiteFriendId());
      result = result && (getApplyResult()
          == other.getApplyResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_FRIEND_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteFriendId().hashCode();
      hash = (37 * hash) + APPLY_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getApplyResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiFriendApplyResultRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiFriendApplyResultRequest)
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.class, com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteFriendId_ = "";

        applyResult_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultRequest_descriptor;
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest build() {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest buildPartial() {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest result = new com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest(this);
        result.siteFriendId_ = siteFriendId_;
        result.applyResult_ = applyResult_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest) {
          return mergeFrom((com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest other) {
        if (other == com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest.getDefaultInstance()) return this;
        if (!other.getSiteFriendId().isEmpty()) {
          siteFriendId_ = other.siteFriendId_;
          onChanged();
        }
        if (other.getApplyResult() != false) {
          setApplyResult(other.getApplyResult());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteFriendId_ = "";
      /**
       * <pre>
       *发送好友申请的用户
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public java.lang.String getSiteFriendId() {
        java.lang.Object ref = siteFriendId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteFriendId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送好友申请的用户
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteFriendIdBytes() {
        java.lang.Object ref = siteFriendId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteFriendId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送好友申请的用户
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder setSiteFriendId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteFriendId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送好友申请的用户
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder clearSiteFriendId() {
        
        siteFriendId_ = getDefaultInstance().getSiteFriendId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送好友申请的用户
       * </pre>
       *
       * <code>optional string site_friend_id = 1;</code>
       */
      public Builder setSiteFriendIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteFriendId_ = value;
        onChanged();
        return this;
      }

      private boolean applyResult_ ;
      /**
       * <pre>
       *当前用户处理好友申请的结果
       * </pre>
       *
       * <code>optional bool apply_result = 2;</code>
       */
      public boolean getApplyResult() {
        return applyResult_;
      }
      /**
       * <pre>
       *当前用户处理好友申请的结果
       * </pre>
       *
       * <code>optional bool apply_result = 2;</code>
       */
      public Builder setApplyResult(boolean value) {
        
        applyResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前用户处理好友申请的结果
       * </pre>
       *
       * <code>optional bool apply_result = 2;</code>
       */
      public Builder clearApplyResult() {
        
        applyResult_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiFriendApplyResultRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiFriendApplyResultRequest)
    private static final com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest();
    }

    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiFriendApplyResultRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiFriendApplyResultRequest>() {
      public ApiFriendApplyResultRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiFriendApplyResultRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiFriendApplyResultRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiFriendApplyResultRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiFriendApplyResultResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiFriendApplyResultResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiFriendApplyResultResponse}
   */
  public  static final class ApiFriendApplyResultResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiFriendApplyResultResponse)
      ApiFriendApplyResultResponseOrBuilder {
    // Use ApiFriendApplyResultResponse.newBuilder() to construct.
    private ApiFriendApplyResultResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiFriendApplyResultResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiFriendApplyResultResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.class, com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse other = (com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiFriendApplyResultResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiFriendApplyResultResponse)
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.class, com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.internal_static_site_ApiFriendApplyResultResponse_descriptor;
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse build() {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse buildPartial() {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse result = new com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse) {
          return mergeFrom((com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse other) {
        if (other == com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiFriendApplyResultResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiFriendApplyResultResponse)
    private static final com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse();
    }

    public static com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiFriendApplyResultResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiFriendApplyResultResponse>() {
      public ApiFriendApplyResultResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiFriendApplyResultResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiFriendApplyResultResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiFriendApplyResultResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiFriendApplyResultProto.ApiFriendApplyResultResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiFriendApplyResultRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiFriendApplyResultRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiFriendApplyResultResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiFriendApplyResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!site/api_friend_applyResult.proto\022\004sit" +
      "e\"K\n\033ApiFriendApplyResultRequest\022\026\n\016site" +
      "_friend_id\030\001 \001(\t\022\024\n\014apply_result\030\002 \001(\010\"\036" +
      "\n\034ApiFriendApplyResultResponse2s\n\033ApiFri" +
      "endApplyResultService\022T\n\013applyResult\022!.s" +
      "ite.ApiFriendApplyResultRequest\032\".site.A" +
      "piFriendApplyResultResponseB2\n\025com.akaxi" +
      "n.proto.siteB\031ApiFriendApplyResultProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiFriendApplyResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiFriendApplyResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiFriendApplyResultRequest_descriptor,
        new java.lang.String[] { "SiteFriendId", "ApplyResult", });
    internal_static_site_ApiFriendApplyResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiFriendApplyResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiFriendApplyResultResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
