// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_group_joinByToken.proto

package com.akaxin.proto.site;

public final class ApiGroupJoinByTokenProto {
  private ApiGroupJoinByTokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiGroupJoinByTokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupJoinByTokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *群组id
     * </pre>
     *
     * <code>optional string site_group_id = 1;</code>
     */
    java.lang.String getSiteGroupId();
    /**
     * <pre>
     *群组id
     * </pre>
     *
     * <code>optional string site_group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteGroupIdBytes();

    /**
     * <pre>
     *群token
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *群token
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code site.ApiGroupJoinByTokenRequest}
   */
  public  static final class ApiGroupJoinByTokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupJoinByTokenRequest)
      ApiGroupJoinByTokenRequestOrBuilder {
    // Use ApiGroupJoinByTokenRequest.newBuilder() to construct.
    private ApiGroupJoinByTokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiGroupJoinByTokenRequest() {
      siteGroupId_ = "";
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiGroupJoinByTokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteGroupId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.class, com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.Builder.class);
    }

    public static final int SITE_GROUP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteGroupId_;
    /**
     * <pre>
     *群组id
     * </pre>
     *
     * <code>optional string site_group_id = 1;</code>
     */
    public java.lang.String getSiteGroupId() {
      java.lang.Object ref = siteGroupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteGroupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群组id
     * </pre>
     *
     * <code>optional string site_group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteGroupIdBytes() {
      java.lang.Object ref = siteGroupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *群token
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群token
     * </pre>
     *
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteGroupId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteGroupId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest other = (com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest) obj;

      boolean result = true;
      result = result && getSiteGroupId()
          .equals(other.getSiteGroupId());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteGroupId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiGroupJoinByTokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupJoinByTokenRequest)
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.class, com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteGroupId_ = "";

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenRequest_descriptor;
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest build() {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest buildPartial() {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest result = new com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest(this);
        result.siteGroupId_ = siteGroupId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest) {
          return mergeFrom((com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest other) {
        if (other == com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest.getDefaultInstance()) return this;
        if (!other.getSiteGroupId().isEmpty()) {
          siteGroupId_ = other.siteGroupId_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteGroupId_ = "";
      /**
       * <pre>
       *群组id
       * </pre>
       *
       * <code>optional string site_group_id = 1;</code>
       */
      public java.lang.String getSiteGroupId() {
        java.lang.Object ref = siteGroupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteGroupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群组id
       * </pre>
       *
       * <code>optional string site_group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteGroupIdBytes() {
        java.lang.Object ref = siteGroupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteGroupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群组id
       * </pre>
       *
       * <code>optional string site_group_id = 1;</code>
       */
      public Builder setSiteGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组id
       * </pre>
       *
       * <code>optional string site_group_id = 1;</code>
       */
      public Builder clearSiteGroupId() {
        
        siteGroupId_ = getDefaultInstance().getSiteGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组id
       * </pre>
       *
       * <code>optional string site_group_id = 1;</code>
       */
      public Builder setSiteGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteGroupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *群token
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群token
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群token
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群token
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群token
       * </pre>
       *
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiGroupJoinByTokenRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiGroupJoinByTokenRequest)
    private static final com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest();
    }

    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiGroupJoinByTokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiGroupJoinByTokenRequest>() {
      public ApiGroupJoinByTokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiGroupJoinByTokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiGroupJoinByTokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiGroupJoinByTokenRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiGroupJoinByTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiGroupJoinByTokenResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiGroupJoinByTokenResponse}
   */
  public  static final class ApiGroupJoinByTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiGroupJoinByTokenResponse)
      ApiGroupJoinByTokenResponseOrBuilder {
    // Use ApiGroupJoinByTokenResponse.newBuilder() to construct.
    private ApiGroupJoinByTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiGroupJoinByTokenResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiGroupJoinByTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.class, com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse other = (com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiGroupJoinByTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiGroupJoinByTokenResponse)
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.class, com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.internal_static_site_ApiGroupJoinByTokenResponse_descriptor;
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse build() {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse buildPartial() {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse result = new com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse) {
          return mergeFrom((com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse other) {
        if (other == com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiGroupJoinByTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiGroupJoinByTokenResponse)
    private static final com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse();
    }

    public static com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiGroupJoinByTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiGroupJoinByTokenResponse>() {
      public ApiGroupJoinByTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiGroupJoinByTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiGroupJoinByTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiGroupJoinByTokenResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiGroupJoinByTokenProto.ApiGroupJoinByTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiGroupJoinByTokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiGroupJoinByTokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiGroupJoinByTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiGroupJoinByTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n site/api_group_joinByToken.proto\022\004site" +
      "\032\020core/group.proto\"B\n\032ApiGroupJoinByToke" +
      "nRequest\022\025\n\rsite_group_id\030\001 \001(\t\022\r\n\005token" +
      "\030\002 \001(\t\"\035\n\033ApiGroupJoinByTokenResponse2p\n" +
      "\032ApiGroupJoinByTokenService\022R\n\013joinByTok" +
      "en\022 .site.ApiGroupJoinByTokenRequest\032!.s" +
      "ite.ApiGroupJoinByTokenResponseB1\n\025com.a" +
      "kaxin.proto.siteB\030ApiGroupJoinByTokenPro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akaxin.proto.core.GroupProto.getDescriptor(),
        }, assigner);
    internal_static_site_ApiGroupJoinByTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiGroupJoinByTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiGroupJoinByTokenRequest_descriptor,
        new java.lang.String[] { "SiteGroupId", "Token", });
    internal_static_site_ApiGroupJoinByTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiGroupJoinByTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiGroupJoinByTokenResponse_descriptor,
        new java.lang.String[] { });
    com.akaxin.proto.core.GroupProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
