// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_site_register.proto

package com.akaxin.proto.site;

public final class ApiSiteRegisterProto {
  private ApiSiteRegisterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiSiteRegisterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSiteRegisterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string user_name = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string user_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    java.lang.String getUserPhoto();
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPhotoBytes();

    /**
     * <pre>
     *用户邀请码
     * </pre>
     *
     * <code>optional string user_uic = 4;</code>
     */
    java.lang.String getUserUic();
    /**
     * <pre>
     *用户邀请码
     * </pre>
     *
     * <code>optional string user_uic = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserUicBytes();

    /**
     * <pre>
     *注册申请信息
     * </pre>
     *
     * <code>optional string apply_info = 5;</code>
     */
    java.lang.String getApplyInfo();
    /**
     * <pre>
     *注册申请信息
     * </pre>
     *
     * <code>optional string apply_info = 5;</code>
     */
    com.google.protobuf.ByteString
        getApplyInfoBytes();

    /**
     * <pre>
     *站点需实名时，提供的平台手机令牌（授权码）
     * </pre>
     *
     * <code>optional string phone_token = 6;</code>
     */
    java.lang.String getPhoneToken();
    /**
     * <pre>
     *站点需实名时，提供的平台手机令牌（授权码）
     * </pre>
     *
     * <code>optional string phone_token = 6;</code>
     */
    com.google.protobuf.ByteString
        getPhoneTokenBytes();

    /**
     * <pre>
     *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
     * </pre>
     *
     * <code>optional string site_login_id = 7;</code>
     */
    java.lang.String getSiteLoginId();
    /**
     * <pre>
     *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
     * </pre>
     *
     * <code>optional string site_login_id = 7;</code>
     */
    com.google.protobuf.ByteString
        getSiteLoginIdBytes();
  }
  /**
   * Protobuf type {@code site.ApiSiteRegisterRequest}
   */
  public  static final class ApiSiteRegisterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSiteRegisterRequest)
      ApiSiteRegisterRequestOrBuilder {
    // Use ApiSiteRegisterRequest.newBuilder() to construct.
    private ApiSiteRegisterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSiteRegisterRequest() {
      userIdPubk_ = "";
      userName_ = "";
      userPhoto_ = "";
      userUic_ = "";
      applyInfo_ = "";
      phoneToken_ = "";
      siteLoginId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiSiteRegisterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhoto_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userUic_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              applyInfo_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneToken_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              siteLoginId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.class, com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.Builder.class);
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>optional string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PHOTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPhoto_;
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_UIC_FIELD_NUMBER = 4;
    private volatile java.lang.Object userUic_;
    /**
     * <pre>
     *用户邀请码
     * </pre>
     *
     * <code>optional string user_uic = 4;</code>
     */
    public java.lang.String getUserUic() {
      java.lang.Object ref = userUic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userUic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户邀请码
     * </pre>
     *
     * <code>optional string user_uic = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserUicBytes() {
      java.lang.Object ref = userUic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userUic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLY_INFO_FIELD_NUMBER = 5;
    private volatile java.lang.Object applyInfo_;
    /**
     * <pre>
     *注册申请信息
     * </pre>
     *
     * <code>optional string apply_info = 5;</code>
     */
    public java.lang.String getApplyInfo() {
      java.lang.Object ref = applyInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applyInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *注册申请信息
     * </pre>
     *
     * <code>optional string apply_info = 5;</code>
     */
    public com.google.protobuf.ByteString
        getApplyInfoBytes() {
      java.lang.Object ref = applyInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applyInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_TOKEN_FIELD_NUMBER = 6;
    private volatile java.lang.Object phoneToken_;
    /**
     * <pre>
     *站点需实名时，提供的平台手机令牌（授权码）
     * </pre>
     *
     * <code>optional string phone_token = 6;</code>
     */
    public java.lang.String getPhoneToken() {
      java.lang.Object ref = phoneToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点需实名时，提供的平台手机令牌（授权码）
     * </pre>
     *
     * <code>optional string phone_token = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneTokenBytes() {
      java.lang.Object ref = phoneToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_LOGIN_ID_FIELD_NUMBER = 7;
    private volatile java.lang.Object siteLoginId_;
    /**
     * <pre>
     *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
     * </pre>
     *
     * <code>optional string site_login_id = 7;</code>
     */
    public java.lang.String getSiteLoginId() {
      java.lang.Object ref = siteLoginId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteLoginId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
     * </pre>
     *
     * <code>optional string site_login_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSiteLoginIdBytes() {
      java.lang.Object ref = siteLoginId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteLoginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPubk_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhoto_);
      }
      if (!getUserUicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userUic_);
      }
      if (!getApplyInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, applyInfo_);
      }
      if (!getPhoneTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, phoneToken_);
      }
      if (!getSiteLoginIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, siteLoginId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPubk_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhoto_);
      }
      if (!getUserUicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userUic_);
      }
      if (!getApplyInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, applyInfo_);
      }
      if (!getPhoneTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, phoneToken_);
      }
      if (!getSiteLoginIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, siteLoginId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest other = (com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest) obj;

      boolean result = true;
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPhoto()
          .equals(other.getUserPhoto());
      result = result && getUserUic()
          .equals(other.getUserUic());
      result = result && getApplyInfo()
          .equals(other.getApplyInfo());
      result = result && getPhoneToken()
          .equals(other.getPhoneToken());
      result = result && getSiteLoginId()
          .equals(other.getSiteLoginId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhoto().hashCode();
      hash = (37 * hash) + USER_UIC_FIELD_NUMBER;
      hash = (53 * hash) + getUserUic().hashCode();
      hash = (37 * hash) + APPLY_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getApplyInfo().hashCode();
      hash = (37 * hash) + PHONE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneToken().hashCode();
      hash = (37 * hash) + SITE_LOGIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteLoginId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSiteRegisterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSiteRegisterRequest)
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.class, com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPubk_ = "";

        userName_ = "";

        userPhoto_ = "";

        userUic_ = "";

        applyInfo_ = "";

        phoneToken_ = "";

        siteLoginId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterRequest_descriptor;
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest build() {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest buildPartial() {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest result = new com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest(this);
        result.userIdPubk_ = userIdPubk_;
        result.userName_ = userName_;
        result.userPhoto_ = userPhoto_;
        result.userUic_ = userUic_;
        result.applyInfo_ = applyInfo_;
        result.phoneToken_ = phoneToken_;
        result.siteLoginId_ = siteLoginId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest) {
          return mergeFrom((com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest other) {
        if (other == com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPhoto().isEmpty()) {
          userPhoto_ = other.userPhoto_;
          onChanged();
        }
        if (!other.getUserUic().isEmpty()) {
          userUic_ = other.userUic_;
          onChanged();
        }
        if (!other.getApplyInfo().isEmpty()) {
          applyInfo_ = other.applyInfo_;
          onChanged();
        }
        if (!other.getPhoneToken().isEmpty()) {
          phoneToken_ = other.phoneToken_;
          onChanged();
        }
        if (!other.getSiteLoginId().isEmpty()) {
          siteLoginId_ = other.siteLoginId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string user_name = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string user_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string user_name = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPhoto_ = "";
      /**
       * <pre>
       *用户头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public java.lang.String getUserPhoto() {
        java.lang.Object ref = userPhoto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhoto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPhotoBytes() {
        java.lang.Object ref = userPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder setUserPhoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhoto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder clearUserPhoto() {
        
        userPhoto_ = getDefaultInstance().getUserPhoto();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder setUserPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhoto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userUic_ = "";
      /**
       * <pre>
       *用户邀请码
       * </pre>
       *
       * <code>optional string user_uic = 4;</code>
       */
      public java.lang.String getUserUic() {
        java.lang.Object ref = userUic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userUic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户邀请码
       * </pre>
       *
       * <code>optional string user_uic = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserUicBytes() {
        java.lang.Object ref = userUic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userUic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户邀请码
       * </pre>
       *
       * <code>optional string user_uic = 4;</code>
       */
      public Builder setUserUic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userUic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户邀请码
       * </pre>
       *
       * <code>optional string user_uic = 4;</code>
       */
      public Builder clearUserUic() {
        
        userUic_ = getDefaultInstance().getUserUic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户邀请码
       * </pre>
       *
       * <code>optional string user_uic = 4;</code>
       */
      public Builder setUserUicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userUic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object applyInfo_ = "";
      /**
       * <pre>
       *注册申请信息
       * </pre>
       *
       * <code>optional string apply_info = 5;</code>
       */
      public java.lang.String getApplyInfo() {
        java.lang.Object ref = applyInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applyInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *注册申请信息
       * </pre>
       *
       * <code>optional string apply_info = 5;</code>
       */
      public com.google.protobuf.ByteString
          getApplyInfoBytes() {
        java.lang.Object ref = applyInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applyInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *注册申请信息
       * </pre>
       *
       * <code>optional string apply_info = 5;</code>
       */
      public Builder setApplyInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applyInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注册申请信息
       * </pre>
       *
       * <code>optional string apply_info = 5;</code>
       */
      public Builder clearApplyInfo() {
        
        applyInfo_ = getDefaultInstance().getApplyInfo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注册申请信息
       * </pre>
       *
       * <code>optional string apply_info = 5;</code>
       */
      public Builder setApplyInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applyInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneToken_ = "";
      /**
       * <pre>
       *站点需实名时，提供的平台手机令牌（授权码）
       * </pre>
       *
       * <code>optional string phone_token = 6;</code>
       */
      public java.lang.String getPhoneToken() {
        java.lang.Object ref = phoneToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点需实名时，提供的平台手机令牌（授权码）
       * </pre>
       *
       * <code>optional string phone_token = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneTokenBytes() {
        java.lang.Object ref = phoneToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点需实名时，提供的平台手机令牌（授权码）
       * </pre>
       *
       * <code>optional string phone_token = 6;</code>
       */
      public Builder setPhoneToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点需实名时，提供的平台手机令牌（授权码）
       * </pre>
       *
       * <code>optional string phone_token = 6;</code>
       */
      public Builder clearPhoneToken() {
        
        phoneToken_ = getDefaultInstance().getPhoneToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点需实名时，提供的平台手机令牌（授权码）
       * </pre>
       *
       * <code>optional string phone_token = 6;</code>
       */
      public Builder setPhoneTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteLoginId_ = "";
      /**
       * <pre>
       *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
       * </pre>
       *
       * <code>optional string site_login_id = 7;</code>
       */
      public java.lang.String getSiteLoginId() {
        java.lang.Object ref = siteLoginId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteLoginId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
       * </pre>
       *
       * <code>optional string site_login_id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSiteLoginIdBytes() {
        java.lang.Object ref = siteLoginId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteLoginId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
       * </pre>
       *
       * <code>optional string site_login_id = 7;</code>
       */
      public Builder setSiteLoginId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteLoginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
       * </pre>
       *
       * <code>optional string site_login_id = 7;</code>
       */
      public Builder clearSiteLoginId() {
        
        siteLoginId_ = getDefaultInstance().getSiteLoginId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登陆用户账号（只允许字符串开头，数字组成6～20位）（选填）
       * </pre>
       *
       * <code>optional string site_login_id = 7;</code>
       */
      public Builder setSiteLoginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteLoginId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSiteRegisterRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSiteRegisterRequest)
    private static final com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest();
    }

    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSiteRegisterRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiSiteRegisterRequest>() {
      public ApiSiteRegisterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiSiteRegisterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSiteRegisterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSiteRegisterRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiSiteRegisterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSiteRegisterResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    java.lang.String getSiteUserId();
    /**
     * <pre>
     *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();
  }
  /**
   * Protobuf type {@code site.ApiSiteRegisterResponse}
   */
  public  static final class ApiSiteRegisterResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSiteRegisterResponse)
      ApiSiteRegisterResponseOrBuilder {
    // Use ApiSiteRegisterResponse.newBuilder() to construct.
    private ApiSiteRegisterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSiteRegisterResponse() {
      siteUserId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiSiteRegisterResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteUserId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.class, com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.Builder.class);
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteUserId_;
    /**
     * <pre>
     *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public java.lang.String getSiteUserId() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteUserId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteUserId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse other = (com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse) obj;

      boolean result = true;
      result = result && getSiteUserId()
          .equals(other.getSiteUserId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSiteRegisterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSiteRegisterResponse)
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.class, com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteUserId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.internal_static_site_ApiSiteRegisterResponse_descriptor;
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse build() {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse buildPartial() {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse result = new com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse(this);
        result.siteUserId_ = siteUserId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse) {
          return mergeFrom((com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse other) {
        if (other == com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse.getDefaultInstance()) return this;
        if (!other.getSiteUserId().isEmpty()) {
          siteUserId_ = other.siteUserId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteUserId_ = "";
      /**
       * <pre>
       *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public java.lang.String getSiteUserId() {
        java.lang.Object ref = siteUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        java.lang.Object ref = siteUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder clearSiteUserId() {
        
        siteUserId_ = getDefaultInstance().getSiteUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回用户在站点的用户ID,后期登陆以及其他情况使用。节省使用公钥的传输消费
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteUserId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSiteRegisterResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSiteRegisterResponse)
    private static final com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse();
    }

    public static com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSiteRegisterResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiSiteRegisterResponse>() {
      public ApiSiteRegisterResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiSiteRegisterResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSiteRegisterResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSiteRegisterResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiSiteRegisterProto.ApiSiteRegisterResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSiteRegisterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSiteRegisterRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSiteRegisterResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSiteRegisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034site/api_site_register.proto\022\004site\"\247\001\n" +
      "\026ApiSiteRegisterRequest\022\024\n\014user_id_pubk\030" +
      "\001 \001(\t\022\021\n\tuser_name\030\002 \001(\t\022\022\n\nuser_photo\030\003" +
      " \001(\t\022\020\n\010user_uic\030\004 \001(\t\022\022\n\napply_info\030\005 \001" +
      "(\t\022\023\n\013phone_token\030\006 \001(\t\022\025\n\rsite_login_id" +
      "\030\007 \001(\t\"/\n\027ApiSiteRegisterResponse\022\024\n\014sit" +
      "e_user_id\030\001 \001(\t2a\n\026ApiSiteRegisterServic" +
      "e\022G\n\010register\022\034.site.ApiSiteRegisterRequ" +
      "est\032\035.site.ApiSiteRegisterResponseB-\n\025co" +
      "m.akaxin.proto.siteB\024ApiSiteRegisterProt",
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiSiteRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiSiteRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSiteRegisterRequest_descriptor,
        new java.lang.String[] { "UserIdPubk", "UserName", "UserPhoto", "UserUic", "ApplyInfo", "PhoneToken", "SiteLoginId", });
    internal_static_site_ApiSiteRegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiSiteRegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSiteRegisterResponse_descriptor,
        new java.lang.String[] { "SiteUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
