// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_user_updateSetting.proto

package com.akaxin.proto.site;

public final class ApiUserUpdateSettingProto {
  private ApiUserUpdateSettingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiUserUpdateSettingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiUserUpdateSettingRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *需要设置的个人信息
   * </pre>
   *
   * Protobuf type {@code site.ApiUserUpdateSettingRequest}
   */
  public  static final class ApiUserUpdateSettingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiUserUpdateSettingRequest)
      ApiUserUpdateSettingRequestOrBuilder {
    // Use ApiUserUpdateSettingRequest.newBuilder() to construct.
    private ApiUserUpdateSettingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserUpdateSettingRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserUpdateSettingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.class, com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest other = (com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *需要设置的个人信息
     * </pre>
     *
     * Protobuf type {@code site.ApiUserUpdateSettingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiUserUpdateSettingRequest)
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.class, com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingRequest_descriptor;
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest build() {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest buildPartial() {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest result = new com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest) {
          return mergeFrom((com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest other) {
        if (other == com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiUserUpdateSettingRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiUserUpdateSettingRequest)
    private static final com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest();
    }

    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserUpdateSettingRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserUpdateSettingRequest>() {
      public ApiUserUpdateSettingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserUpdateSettingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserUpdateSettingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserUpdateSettingRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiUserUpdateSettingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiUserUpdateSettingResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiUserUpdateSettingResponse}
   */
  public  static final class ApiUserUpdateSettingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiUserUpdateSettingResponse)
      ApiUserUpdateSettingResponseOrBuilder {
    // Use ApiUserUpdateSettingResponse.newBuilder() to construct.
    private ApiUserUpdateSettingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserUpdateSettingResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserUpdateSettingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.class, com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse other = (com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiUserUpdateSettingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiUserUpdateSettingResponse)
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.class, com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.internal_static_site_ApiUserUpdateSettingResponse_descriptor;
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse build() {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse buildPartial() {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse result = new com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse) {
          return mergeFrom((com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse other) {
        if (other == com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiUserUpdateSettingResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiUserUpdateSettingResponse)
    private static final com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse();
    }

    public static com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserUpdateSettingResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserUpdateSettingResponse>() {
      public ApiUserUpdateSettingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserUpdateSettingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserUpdateSettingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserUpdateSettingResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiUserUpdateSettingProto.ApiUserUpdateSettingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiUserUpdateSettingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiUserUpdateSettingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiUserUpdateSettingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiUserUpdateSettingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!site/api_user_updateSetting.proto\022\004sit" +
      "e\032\017core/user.proto\"\035\n\033ApiUserUpdateSetti" +
      "ngRequest\"\036\n\034ApiUserUpdateSettingRespons" +
      "e2u\n\033ApiUserUpdateSettingService\022V\n\rupda" +
      "teSetting\022!.site.ApiUserUpdateSettingReq" +
      "uest\032\".site.ApiUserUpdateSettingResponse" +
      "B2\n\025com.akaxin.proto.siteB\031ApiUserUpdate" +
      "SettingProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akaxin.proto.core.UserProto.getDescriptor(),
        }, assigner);
    internal_static_site_ApiUserUpdateSettingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiUserUpdateSettingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiUserUpdateSettingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_site_ApiUserUpdateSettingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiUserUpdateSettingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiUserUpdateSettingResponse_descriptor,
        new java.lang.String[] { });
    com.akaxin.proto.core.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
