// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin/hai_group_checkMember.proto

package com.akaxin.proto.plugin;

public final class HaiGroupCheckMemberProto {
  private HaiGroupCheckMemberProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HaiGroupCheckMemberRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupCheckMemberRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    java.util.List<java.lang.String>
        getSiteUserIdList();
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    int getSiteUserIdCount();
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    java.lang.String getSiteUserId(int index);
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes(int index);
  }
  /**
   * <pre>
   **
   *检查用户是否在某群里
   *----
   *接口名
   *----
   * /hai/group/checkMember
   *错误码
   *----
   * success
   * error.alert
   * </pre>
   *
   * Protobuf type {@code plugin.HaiGroupCheckMemberRequest}
   */
  public  static final class HaiGroupCheckMemberRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupCheckMemberRequest)
      HaiGroupCheckMemberRequestOrBuilder {
    // Use HaiGroupCheckMemberRequest.newBuilder() to construct.
    private HaiGroupCheckMemberRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupCheckMemberRequest() {
      groupId_ = "";
      siteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupCheckMemberRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                siteUserId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              siteUserId_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          siteUserId_ = siteUserId_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.class, com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object groupId_;
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList siteUserId_;
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSiteUserIdList() {
      return siteUserId_;
    }
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    public int getSiteUserIdCount() {
      return siteUserId_.size();
    }
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    public java.lang.String getSiteUserId(int index) {
      return siteUserId_.get(index);
    }
    /**
     * <pre>
     * 待检查的成员id
     * </pre>
     *
     * <code>repeated string site_user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes(int index) {
      return siteUserId_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupId_);
      }
      for (int i = 0; i < siteUserId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, siteUserId_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < siteUserId_.size(); i++) {
          dataSize += computeStringSizeNoTag(siteUserId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSiteUserIdList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest other = (com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest) obj;

      boolean result = true;
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && getSiteUserIdList()
          .equals(other.getSiteUserIdList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      if (getSiteUserIdCount() > 0) {
        hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSiteUserIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *检查用户是否在某群里
     *----
     *接口名
     *----
     * /hai/group/checkMember
     *错误码
     *----
     * success
     * error.alert
     * </pre>
     *
     * Protobuf type {@code plugin.HaiGroupCheckMemberRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupCheckMemberRequest)
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.class, com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = "";

        siteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberRequest_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest build() {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest buildPartial() {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest result = new com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.groupId_ = groupId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          siteUserId_ = siteUserId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.siteUserId_ = siteUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest other) {
        if (other == com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest.getDefaultInstance()) return this;
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.siteUserId_.isEmpty()) {
          if (siteUserId_.isEmpty()) {
            siteUserId_ = other.siteUserId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSiteUserIdIsMutable();
            siteUserId_.addAll(other.siteUserId_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupId_ = "";
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList siteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSiteUserIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          siteUserId_ = new com.google.protobuf.LazyStringArrayList(siteUserId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSiteUserIdList() {
        return siteUserId_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public int getSiteUserIdCount() {
        return siteUserId_.size();
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public java.lang.String getSiteUserId(int index) {
        return siteUserId_.get(index);
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes(int index) {
        return siteUserId_.getByteString(index);
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public Builder setSiteUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSiteUserIdIsMutable();
        siteUserId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public Builder addSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSiteUserIdIsMutable();
        siteUserId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public Builder addAllSiteUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureSiteUserIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, siteUserId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public Builder clearSiteUserId() {
        siteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 待检查的成员id
       * </pre>
       *
       * <code>repeated string site_user_id = 2;</code>
       */
      public Builder addSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSiteUserIdIsMutable();
        siteUserId_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupCheckMemberRequest)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupCheckMemberRequest)
    private static final com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest();
    }

    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupCheckMemberRequest>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupCheckMemberRequest>() {
      public HaiGroupCheckMemberRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupCheckMemberRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupCheckMemberRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupCheckMemberRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HaiGroupCheckMemberResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupCheckMemberResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    java.util.List<java.lang.String>
        getMembersSiteUserIdList();
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    int getMembersSiteUserIdCount();
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    java.lang.String getMembersSiteUserId(int index);
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMembersSiteUserIdBytes(int index);
  }
  /**
   * Protobuf type {@code plugin.HaiGroupCheckMemberResponse}
   */
  public  static final class HaiGroupCheckMemberResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupCheckMemberResponse)
      HaiGroupCheckMemberResponseOrBuilder {
    // Use HaiGroupCheckMemberResponse.newBuilder() to construct.
    private HaiGroupCheckMemberResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupCheckMemberResponse() {
      membersSiteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupCheckMemberResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                membersSiteUserId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              membersSiteUserId_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          membersSiteUserId_ = membersSiteUserId_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.class, com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.Builder.class);
    }

    public static final int MEMBERS_SITE_USER_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList membersSiteUserId_;
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMembersSiteUserIdList() {
      return membersSiteUserId_;
    }
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    public int getMembersSiteUserIdCount() {
      return membersSiteUserId_.size();
    }
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    public java.lang.String getMembersSiteUserId(int index) {
      return membersSiteUserId_.get(index);
    }
    /**
     * <pre>
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     * </pre>
     *
     * <code>repeated string members_site_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMembersSiteUserIdBytes(int index) {
      return membersSiteUserId_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < membersSiteUserId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, membersSiteUserId_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < membersSiteUserId_.size(); i++) {
          dataSize += computeStringSizeNoTag(membersSiteUserId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMembersSiteUserIdList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse other = (com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse) obj;

      boolean result = true;
      result = result && getMembersSiteUserIdList()
          .equals(other.getMembersSiteUserIdList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getMembersSiteUserIdCount() > 0) {
        hash = (37 * hash) + MEMBERS_SITE_USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMembersSiteUserIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code plugin.HaiGroupCheckMemberResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupCheckMemberResponse)
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.class, com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        membersSiteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.internal_static_plugin_HaiGroupCheckMemberResponse_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse build() {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse buildPartial() {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse result = new com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          membersSiteUserId_ = membersSiteUserId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.membersSiteUserId_ = membersSiteUserId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse other) {
        if (other == com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse.getDefaultInstance()) return this;
        if (!other.membersSiteUserId_.isEmpty()) {
          if (membersSiteUserId_.isEmpty()) {
            membersSiteUserId_ = other.membersSiteUserId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembersSiteUserIdIsMutable();
            membersSiteUserId_.addAll(other.membersSiteUserId_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList membersSiteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMembersSiteUserIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          membersSiteUserId_ = new com.google.protobuf.LazyStringArrayList(membersSiteUserId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMembersSiteUserIdList() {
        return membersSiteUserId_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public int getMembersSiteUserIdCount() {
        return membersSiteUserId_.size();
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public java.lang.String getMembersSiteUserId(int index) {
        return membersSiteUserId_.get(index);
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMembersSiteUserIdBytes(int index) {
        return membersSiteUserId_.getByteString(index);
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public Builder setMembersSiteUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersSiteUserIdIsMutable();
        membersSiteUserId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public Builder addMembersSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersSiteUserIdIsMutable();
        membersSiteUserId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public Builder addAllMembersSiteUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureMembersSiteUserIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, membersSiteUserId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public Builder clearMembersSiteUserId() {
        membersSiteUserId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求在这个群里的成员( 肯定是request参数的子集 )
       * </pre>
       *
       * <code>repeated string members_site_user_id = 1;</code>
       */
      public Builder addMembersSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMembersSiteUserIdIsMutable();
        membersSiteUserId_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupCheckMemberResponse)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupCheckMemberResponse)
    private static final com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse();
    }

    public static com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupCheckMemberResponse>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupCheckMemberResponse>() {
      public HaiGroupCheckMemberResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupCheckMemberResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupCheckMemberResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupCheckMemberResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupCheckMemberProto.HaiGroupCheckMemberResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupCheckMemberRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupCheckMemberRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupCheckMemberResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupCheckMemberResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"plugin/hai_group_checkMember.proto\022\006pl" +
      "ugin\"D\n\032HaiGroupCheckMemberRequest\022\020\n\010gr" +
      "oup_id\030\001 \001(\t\022\024\n\014site_user_id\030\002 \003(\t\";\n\033Ha" +
      "iGroupCheckMemberResponse\022\034\n\024members_sit" +
      "e_user_id\030\001 \003(\t2t\n\032HaiGroupCheckMemberSe" +
      "rvice\022V\n\013checkMember\022\".plugin.HaiGroupCh" +
      "eckMemberRequest\032#.plugin.HaiGroupCheckM" +
      "emberResponseB3\n\027com.akaxin.proto.plugin" +
      "B\030HaiGroupCheckMemberProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_plugin_HaiGroupCheckMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_plugin_HaiGroupCheckMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupCheckMemberRequest_descriptor,
        new java.lang.String[] { "GroupId", "SiteUserId", });
    internal_static_plugin_HaiGroupCheckMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_plugin_HaiGroupCheckMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupCheckMemberResponse_descriptor,
        new java.lang.String[] { "MembersSiteUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
