// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin/hai_group_list.proto

package com.akaxin.proto.plugin;

public final class HaiGroupListProto {
  private HaiGroupListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HaiGroupListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *第几页
     * </pre>
     *
     * <code>optional int32 page_number = 1;</code>
     */
    int getPageNumber();

    /**
     * <pre>
     *每页的条数，默认100
     * </pre>
     *
     * <code>optional int32 page_size = 2;</code>
     */
    int getPageSize();
  }
  /**
   * <pre>
   **
   *获取群组列表
   *----
   *接口名
   *----
   * /hai/group/list
   *错误码
   *----
   *- success
   *- error.alert
   * </pre>
   *
   * Protobuf type {@code plugin.HaiGroupListRequest}
   */
  public  static final class HaiGroupListRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupListRequest)
      HaiGroupListRequestOrBuilder {
    // Use HaiGroupListRequest.newBuilder() to construct.
    private HaiGroupListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupListRequest() {
      pageNumber_ = 0;
      pageSize_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupListRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pageNumber_ = input.readInt32();
              break;
            }
            case 16: {

              pageSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.class, com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.Builder.class);
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 1;
    private int pageNumber_;
    /**
     * <pre>
     *第几页
     * </pre>
     *
     * <code>optional int32 page_number = 1;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int PAGE_SIZE_FIELD_NUMBER = 2;
    private int pageSize_;
    /**
     * <pre>
     *每页的条数，默认100
     * </pre>
     *
     * <code>optional int32 page_size = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageNumber_ != 0) {
        output.writeInt32(1, pageNumber_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(2, pageSize_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageNumber_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest other = (com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest) obj;

      boolean result = true;
      result = result && (getPageNumber()
          == other.getPageNumber());
      result = result && (getPageSize()
          == other.getPageSize());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPageNumber();
      hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *获取群组列表
     *----
     *接口名
     *----
     * /hai/group/list
     *错误码
     *----
     *- success
     *- error.alert
     * </pre>
     *
     * Protobuf type {@code plugin.HaiGroupListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupListRequest)
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.class, com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pageNumber_ = 0;

        pageSize_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListRequest_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest build() {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest buildPartial() {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest result = new com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest(this);
        result.pageNumber_ = pageNumber_;
        result.pageSize_ = pageSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest other) {
        if (other == com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest.getDefaultInstance()) return this;
        if (other.getPageNumber() != 0) {
          setPageNumber(other.getPageNumber());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageNumber_ ;
      /**
       * <pre>
       *第几页
       * </pre>
       *
       * <code>optional int32 page_number = 1;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <pre>
       *第几页
       * </pre>
       *
       * <code>optional int32 page_number = 1;</code>
       */
      public Builder setPageNumber(int value) {
        
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *第几页
       * </pre>
       *
       * <code>optional int32 page_number = 1;</code>
       */
      public Builder clearPageNumber() {
        
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <pre>
       *每页的条数，默认100
       * </pre>
       *
       * <code>optional int32 page_size = 2;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <pre>
       *每页的条数，默认100
       * </pre>
       *
       * <code>optional int32 page_size = 2;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每页的条数，默认100
       * </pre>
       *
       * <code>optional int32 page_size = 2;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupListRequest)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupListRequest)
    private static final com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest();
    }

    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupListRequest>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupListRequest>() {
      public HaiGroupListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupListRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupListRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupListRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HaiGroupListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile> 
        getGroupProfileList();
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    com.akaxin.proto.core.GroupProto.SimpleGroupProfile getGroupProfile(int index);
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    int getGroupProfileCount();
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    java.util.List<? extends com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder> 
        getGroupProfileOrBuilderList();
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder getGroupProfileOrBuilder(
        int index);

    /**
     * <pre>
     * 一共多少页
     * </pre>
     *
     * <code>optional int32 page_total_num = 2;</code>
     */
    int getPageTotalNum();
  }
  /**
   * Protobuf type {@code plugin.HaiGroupListResponse}
   */
  public  static final class HaiGroupListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupListResponse)
      HaiGroupListResponseOrBuilder {
    // Use HaiGroupListResponse.newBuilder() to construct.
    private HaiGroupListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupListResponse() {
      groupProfile_ = java.util.Collections.emptyList();
      pageTotalNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                groupProfile_ = new java.util.ArrayList<com.akaxin.proto.core.GroupProto.SimpleGroupProfile>();
                mutable_bitField0_ |= 0x00000001;
              }
              groupProfile_.add(
                  input.readMessage(com.akaxin.proto.core.GroupProto.SimpleGroupProfile.parser(), extensionRegistry));
              break;
            }
            case 16: {

              pageTotalNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          groupProfile_ = java.util.Collections.unmodifiableList(groupProfile_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.class, com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_PROFILE_FIELD_NUMBER = 1;
    private java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile> groupProfile_;
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    public java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile> getGroupProfileList() {
      return groupProfile_;
    }
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    public java.util.List<? extends com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder> 
        getGroupProfileOrBuilderList() {
      return groupProfile_;
    }
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    public int getGroupProfileCount() {
      return groupProfile_.size();
    }
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    public com.akaxin.proto.core.GroupProto.SimpleGroupProfile getGroupProfile(int index) {
      return groupProfile_.get(index);
    }
    /**
     * <pre>
     *用户的群列表
     * </pre>
     *
     * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
     */
    public com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder getGroupProfileOrBuilder(
        int index) {
      return groupProfile_.get(index);
    }

    public static final int PAGE_TOTAL_NUM_FIELD_NUMBER = 2;
    private int pageTotalNum_;
    /**
     * <pre>
     * 一共多少页
     * </pre>
     *
     * <code>optional int32 page_total_num = 2;</code>
     */
    public int getPageTotalNum() {
      return pageTotalNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < groupProfile_.size(); i++) {
        output.writeMessage(1, groupProfile_.get(i));
      }
      if (pageTotalNum_ != 0) {
        output.writeInt32(2, pageTotalNum_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < groupProfile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, groupProfile_.get(i));
      }
      if (pageTotalNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageTotalNum_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse other = (com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse) obj;

      boolean result = true;
      result = result && getGroupProfileList()
          .equals(other.getGroupProfileList());
      result = result && (getPageTotalNum()
          == other.getPageTotalNum());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getGroupProfileCount() > 0) {
        hash = (37 * hash) + GROUP_PROFILE_FIELD_NUMBER;
        hash = (53 * hash) + getGroupProfileList().hashCode();
      }
      hash = (37 * hash) + PAGE_TOTAL_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getPageTotalNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code plugin.HaiGroupListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupListResponse)
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.class, com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGroupProfileFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (groupProfileBuilder_ == null) {
          groupProfile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          groupProfileBuilder_.clear();
        }
        pageTotalNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupListProto.internal_static_plugin_HaiGroupListResponse_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse build() {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse buildPartial() {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse result = new com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (groupProfileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            groupProfile_ = java.util.Collections.unmodifiableList(groupProfile_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.groupProfile_ = groupProfile_;
        } else {
          result.groupProfile_ = groupProfileBuilder_.build();
        }
        result.pageTotalNum_ = pageTotalNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse other) {
        if (other == com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse.getDefaultInstance()) return this;
        if (groupProfileBuilder_ == null) {
          if (!other.groupProfile_.isEmpty()) {
            if (groupProfile_.isEmpty()) {
              groupProfile_ = other.groupProfile_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGroupProfileIsMutable();
              groupProfile_.addAll(other.groupProfile_);
            }
            onChanged();
          }
        } else {
          if (!other.groupProfile_.isEmpty()) {
            if (groupProfileBuilder_.isEmpty()) {
              groupProfileBuilder_.dispose();
              groupProfileBuilder_ = null;
              groupProfile_ = other.groupProfile_;
              bitField0_ = (bitField0_ & ~0x00000001);
              groupProfileBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGroupProfileFieldBuilder() : null;
            } else {
              groupProfileBuilder_.addAllMessages(other.groupProfile_);
            }
          }
        }
        if (other.getPageTotalNum() != 0) {
          setPageTotalNum(other.getPageTotalNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile> groupProfile_ =
        java.util.Collections.emptyList();
      private void ensureGroupProfileIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          groupProfile_ = new java.util.ArrayList<com.akaxin.proto.core.GroupProto.SimpleGroupProfile>(groupProfile_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akaxin.proto.core.GroupProto.SimpleGroupProfile, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder, com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder> groupProfileBuilder_;

      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile> getGroupProfileList() {
        if (groupProfileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groupProfile_);
        } else {
          return groupProfileBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public int getGroupProfileCount() {
        if (groupProfileBuilder_ == null) {
          return groupProfile_.size();
        } else {
          return groupProfileBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public com.akaxin.proto.core.GroupProto.SimpleGroupProfile getGroupProfile(int index) {
        if (groupProfileBuilder_ == null) {
          return groupProfile_.get(index);
        } else {
          return groupProfileBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder setGroupProfile(
          int index, com.akaxin.proto.core.GroupProto.SimpleGroupProfile value) {
        if (groupProfileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupProfileIsMutable();
          groupProfile_.set(index, value);
          onChanged();
        } else {
          groupProfileBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder setGroupProfile(
          int index, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder builderForValue) {
        if (groupProfileBuilder_ == null) {
          ensureGroupProfileIsMutable();
          groupProfile_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupProfileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder addGroupProfile(com.akaxin.proto.core.GroupProto.SimpleGroupProfile value) {
        if (groupProfileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupProfileIsMutable();
          groupProfile_.add(value);
          onChanged();
        } else {
          groupProfileBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder addGroupProfile(
          int index, com.akaxin.proto.core.GroupProto.SimpleGroupProfile value) {
        if (groupProfileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupProfileIsMutable();
          groupProfile_.add(index, value);
          onChanged();
        } else {
          groupProfileBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder addGroupProfile(
          com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder builderForValue) {
        if (groupProfileBuilder_ == null) {
          ensureGroupProfileIsMutable();
          groupProfile_.add(builderForValue.build());
          onChanged();
        } else {
          groupProfileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder addGroupProfile(
          int index, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder builderForValue) {
        if (groupProfileBuilder_ == null) {
          ensureGroupProfileIsMutable();
          groupProfile_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupProfileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder addAllGroupProfile(
          java.lang.Iterable<? extends com.akaxin.proto.core.GroupProto.SimpleGroupProfile> values) {
        if (groupProfileBuilder_ == null) {
          ensureGroupProfileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, groupProfile_);
          onChanged();
        } else {
          groupProfileBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder clearGroupProfile() {
        if (groupProfileBuilder_ == null) {
          groupProfile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          groupProfileBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public Builder removeGroupProfile(int index) {
        if (groupProfileBuilder_ == null) {
          ensureGroupProfileIsMutable();
          groupProfile_.remove(index);
          onChanged();
        } else {
          groupProfileBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder getGroupProfileBuilder(
          int index) {
        return getGroupProfileFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder getGroupProfileOrBuilder(
          int index) {
        if (groupProfileBuilder_ == null) {
          return groupProfile_.get(index);  } else {
          return groupProfileBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public java.util.List<? extends com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder> 
           getGroupProfileOrBuilderList() {
        if (groupProfileBuilder_ != null) {
          return groupProfileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groupProfile_);
        }
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder addGroupProfileBuilder() {
        return getGroupProfileFieldBuilder().addBuilder(
            com.akaxin.proto.core.GroupProto.SimpleGroupProfile.getDefaultInstance());
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder addGroupProfileBuilder(
          int index) {
        return getGroupProfileFieldBuilder().addBuilder(
            index, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.getDefaultInstance());
      }
      /**
       * <pre>
       *用户的群列表
       * </pre>
       *
       * <code>repeated .core.SimpleGroupProfile group_profile = 1;</code>
       */
      public java.util.List<com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder> 
           getGroupProfileBuilderList() {
        return getGroupProfileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akaxin.proto.core.GroupProto.SimpleGroupProfile, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder, com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder> 
          getGroupProfileFieldBuilder() {
        if (groupProfileBuilder_ == null) {
          groupProfileBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.akaxin.proto.core.GroupProto.SimpleGroupProfile, com.akaxin.proto.core.GroupProto.SimpleGroupProfile.Builder, com.akaxin.proto.core.GroupProto.SimpleGroupProfileOrBuilder>(
                  groupProfile_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          groupProfile_ = null;
        }
        return groupProfileBuilder_;
      }

      private int pageTotalNum_ ;
      /**
       * <pre>
       * 一共多少页
       * </pre>
       *
       * <code>optional int32 page_total_num = 2;</code>
       */
      public int getPageTotalNum() {
        return pageTotalNum_;
      }
      /**
       * <pre>
       * 一共多少页
       * </pre>
       *
       * <code>optional int32 page_total_num = 2;</code>
       */
      public Builder setPageTotalNum(int value) {
        
        pageTotalNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 一共多少页
       * </pre>
       *
       * <code>optional int32 page_total_num = 2;</code>
       */
      public Builder clearPageTotalNum() {
        
        pageTotalNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupListResponse)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupListResponse)
    private static final com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse();
    }

    public static com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupListResponse>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupListResponse>() {
      public HaiGroupListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupListResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupListProto.HaiGroupListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupListRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupListRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033plugin/hai_group_list.proto\022\006plugin\032\020c" +
      "ore/group.proto\"=\n\023HaiGroupListRequest\022\023" +
      "\n\013page_number\030\001 \001(\005\022\021\n\tpage_size\030\002 \001(\005\"_" +
      "\n\024HaiGroupListResponse\022/\n\rgroup_profile\030" +
      "\001 \003(\0132\030.core.SimpleGroupProfile\022\026\n\016page_" +
      "total_num\030\002 \001(\0052X\n\023HaiGroupListService\022A" +
      "\n\004list\022\033.plugin.HaiGroupListRequest\032\034.pl" +
      "ugin.HaiGroupListResponseB,\n\027com.akaxin." +
      "proto.pluginB\021HaiGroupListProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akaxin.proto.core.GroupProto.getDescriptor(),
        }, assigner);
    internal_static_plugin_HaiGroupListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_plugin_HaiGroupListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupListRequest_descriptor,
        new java.lang.String[] { "PageNumber", "PageSize", });
    internal_static_plugin_HaiGroupListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_plugin_HaiGroupListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupListResponse_descriptor,
        new java.lang.String[] { "GroupProfile", "PageTotalNum", });
    com.akaxin.proto.core.GroupProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
