// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin/hai_group_addMember.proto

package com.akaxin.proto.plugin;

public final class HaiGroupAddMemberProto {
  private HaiGroupAddMemberProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HaiGroupAddMemberRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupAddMemberRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    java.util.List<java.lang.String>
        getGroupMemberList();
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    int getGroupMemberCount();
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    java.lang.String getGroupMember(int index);
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupMemberBytes(int index);
  }
  /**
   * Protobuf type {@code plugin.HaiGroupAddMemberRequest}
   */
  public  static final class HaiGroupAddMemberRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupAddMemberRequest)
      HaiGroupAddMemberRequestOrBuilder {
    // Use HaiGroupAddMemberRequest.newBuilder() to construct.
    private HaiGroupAddMemberRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupAddMemberRequest() {
      groupId_ = "";
      groupMember_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupAddMemberRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                groupMember_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              groupMember_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          groupMember_ = groupMember_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.class, com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object groupId_;
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群组ID
     * </pre>
     *
     * <code>optional string group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_MEMBER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList groupMember_;
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGroupMemberList() {
      return groupMember_;
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    public int getGroupMemberCount() {
      return groupMember_.size();
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    public java.lang.String getGroupMember(int index) {
      return groupMember_.get(index);
    }
    /**
     * <pre>
     *群组中需要增加的用户ID
     * </pre>
     *
     * <code>repeated string group_member = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupMemberBytes(int index) {
      return groupMember_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupId_);
      }
      for (int i = 0; i < groupMember_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupMember_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupMember_.size(); i++) {
          dataSize += computeStringSizeNoTag(groupMember_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGroupMemberList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest other = (com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest) obj;

      boolean result = true;
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && getGroupMemberList()
          .equals(other.getGroupMemberList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      if (getGroupMemberCount() > 0) {
        hash = (37 * hash) + GROUP_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + getGroupMemberList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code plugin.HaiGroupAddMemberRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupAddMemberRequest)
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.class, com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = "";

        groupMember_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberRequest_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest build() {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest buildPartial() {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest result = new com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.groupId_ = groupId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          groupMember_ = groupMember_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.groupMember_ = groupMember_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest other) {
        if (other == com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest.getDefaultInstance()) return this;
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.groupMember_.isEmpty()) {
          if (groupMember_.isEmpty()) {
            groupMember_ = other.groupMember_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGroupMemberIsMutable();
            groupMember_.addAll(other.groupMember_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupId_ = "";
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组ID
       * </pre>
       *
       * <code>optional string group_id = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList groupMember_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupMemberIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          groupMember_ = new com.google.protobuf.LazyStringArrayList(groupMember_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getGroupMemberList() {
        return groupMember_.getUnmodifiableView();
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public int getGroupMemberCount() {
        return groupMember_.size();
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public java.lang.String getGroupMember(int index) {
        return groupMember_.get(index);
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupMemberBytes(int index) {
        return groupMember_.getByteString(index);
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public Builder setGroupMember(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupMemberIsMutable();
        groupMember_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public Builder addGroupMember(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupMemberIsMutable();
        groupMember_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public Builder addAllGroupMember(
          java.lang.Iterable<java.lang.String> values) {
        ensureGroupMemberIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupMember_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public Builder clearGroupMember() {
        groupMember_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群组中需要增加的用户ID
       * </pre>
       *
       * <code>repeated string group_member = 2;</code>
       */
      public Builder addGroupMemberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureGroupMemberIsMutable();
        groupMember_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupAddMemberRequest)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupAddMemberRequest)
    private static final com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest();
    }

    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupAddMemberRequest>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupAddMemberRequest>() {
      public HaiGroupAddMemberRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupAddMemberRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupAddMemberRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupAddMemberRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HaiGroupAddMemberResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:plugin.HaiGroupAddMemberResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code plugin.HaiGroupAddMemberResponse}
   */
  public  static final class HaiGroupAddMemberResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:plugin.HaiGroupAddMemberResponse)
      HaiGroupAddMemberResponseOrBuilder {
    // Use HaiGroupAddMemberResponse.newBuilder() to construct.
    private HaiGroupAddMemberResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiGroupAddMemberResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiGroupAddMemberResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.class, com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse other = (com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code plugin.HaiGroupAddMemberResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:plugin.HaiGroupAddMemberResponse)
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.class, com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.internal_static_plugin_HaiGroupAddMemberResponse_descriptor;
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse build() {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse buildPartial() {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse result = new com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse) {
          return mergeFrom((com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse other) {
        if (other == com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:plugin.HaiGroupAddMemberResponse)
    }

    // @@protoc_insertion_point(class_scope:plugin.HaiGroupAddMemberResponse)
    private static final com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse();
    }

    public static com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiGroupAddMemberResponse>
        PARSER = new com.google.protobuf.AbstractParser<HaiGroupAddMemberResponse>() {
      public HaiGroupAddMemberResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiGroupAddMemberResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiGroupAddMemberResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiGroupAddMemberResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiGroupAddMemberProto.HaiGroupAddMemberResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupAddMemberRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupAddMemberRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plugin_HaiGroupAddMemberResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plugin_HaiGroupAddMemberResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n plugin/hai_group_addMember.proto\022\006plug" +
      "in\"B\n\030HaiGroupAddMemberRequest\022\020\n\010group_" +
      "id\030\001 \001(\t\022\024\n\014group_member\030\002 \003(\t\"\033\n\031HaiGro" +
      "upAddMemberResponse2l\n\030HaiGroupAddMember" +
      "Service\022P\n\taddMember\022 .plugin.HaiGroupAd" +
      "dMemberRequest\032!.plugin.HaiGroupAddMembe" +
      "rResponseB1\n\027com.akaxin.proto.pluginB\026Ha" +
      "iGroupAddMemberProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_plugin_HaiGroupAddMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_plugin_HaiGroupAddMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupAddMemberRequest_descriptor,
        new java.lang.String[] { "GroupId", "GroupMember", });
    internal_static_plugin_HaiGroupAddMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_plugin_HaiGroupAddMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plugin_HaiGroupAddMemberResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
