// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin/hai_plugin_profile.proto

package com.akaxin.proto.plugin;

public final class HaiPluginProfileProto {
  private HaiPluginProfileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HaiPluginProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.HaiPluginProfileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *插件id
     * </pre>
     *
     * <code>optional string plugin_id = 1;</code>
     */
    java.lang.String getPluginId();
    /**
     * <pre>
     *插件id
     * </pre>
     *
     * <code>optional string plugin_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPluginIdBytes();
  }
  /**
   * Protobuf type {@code site.HaiPluginProfileRequest}
   */
  public  static final class HaiPluginProfileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.HaiPluginProfileRequest)
      HaiPluginProfileRequestOrBuilder {
    // Use HaiPluginProfileRequest.newBuilder() to construct.
    private HaiPluginProfileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiPluginProfileRequest() {
      pluginId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiPluginProfileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pluginId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.class, com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.Builder.class);
    }

    public static final int PLUGIN_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object pluginId_;
    /**
     * <pre>
     *插件id
     * </pre>
     *
     * <code>optional string plugin_id = 1;</code>
     */
    public java.lang.String getPluginId() {
      java.lang.Object ref = pluginId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pluginId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *插件id
     * </pre>
     *
     * <code>optional string plugin_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPluginIdBytes() {
      java.lang.Object ref = pluginId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pluginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPluginIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pluginId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPluginIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pluginId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest other = (com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest) obj;

      boolean result = true;
      result = result && getPluginId()
          .equals(other.getPluginId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PLUGIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPluginId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.HaiPluginProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.HaiPluginProfileRequest)
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.class, com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pluginId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileRequest_descriptor;
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest build() {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest buildPartial() {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest result = new com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest(this);
        result.pluginId_ = pluginId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest) {
          return mergeFrom((com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest other) {
        if (other == com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest.getDefaultInstance()) return this;
        if (!other.getPluginId().isEmpty()) {
          pluginId_ = other.pluginId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pluginId_ = "";
      /**
       * <pre>
       *插件id
       * </pre>
       *
       * <code>optional string plugin_id = 1;</code>
       */
      public java.lang.String getPluginId() {
        java.lang.Object ref = pluginId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pluginId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *插件id
       * </pre>
       *
       * <code>optional string plugin_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPluginIdBytes() {
        java.lang.Object ref = pluginId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pluginId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *插件id
       * </pre>
       *
       * <code>optional string plugin_id = 1;</code>
       */
      public Builder setPluginId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pluginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件id
       * </pre>
       *
       * <code>optional string plugin_id = 1;</code>
       */
      public Builder clearPluginId() {
        
        pluginId_ = getDefaultInstance().getPluginId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *插件id
       * </pre>
       *
       * <code>optional string plugin_id = 1;</code>
       */
      public Builder setPluginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pluginId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.HaiPluginProfileRequest)
    }

    // @@protoc_insertion_point(class_scope:site.HaiPluginProfileRequest)
    private static final com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest();
    }

    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiPluginProfileRequest>
        PARSER = new com.google.protobuf.AbstractParser<HaiPluginProfileRequest>() {
      public HaiPluginProfileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiPluginProfileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiPluginProfileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiPluginProfileRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HaiPluginProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.HaiPluginProfileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    boolean hasPlugin();
    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    com.akaxin.proto.core.PluginProto.Plugin getPlugin();
    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    com.akaxin.proto.core.PluginProto.PluginOrBuilder getPluginOrBuilder();
  }
  /**
   * Protobuf type {@code site.HaiPluginProfileResponse}
   */
  public  static final class HaiPluginProfileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.HaiPluginProfileResponse)
      HaiPluginProfileResponseOrBuilder {
    // Use HaiPluginProfileResponse.newBuilder() to construct.
    private HaiPluginProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HaiPluginProfileResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HaiPluginProfileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.akaxin.proto.core.PluginProto.Plugin.Builder subBuilder = null;
              if (plugin_ != null) {
                subBuilder = plugin_.toBuilder();
              }
              plugin_ = input.readMessage(com.akaxin.proto.core.PluginProto.Plugin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(plugin_);
                plugin_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.class, com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.Builder.class);
    }

    public static final int PLUGIN_FIELD_NUMBER = 1;
    private com.akaxin.proto.core.PluginProto.Plugin plugin_;
    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    public boolean hasPlugin() {
      return plugin_ != null;
    }
    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    public com.akaxin.proto.core.PluginProto.Plugin getPlugin() {
      return plugin_ == null ? com.akaxin.proto.core.PluginProto.Plugin.getDefaultInstance() : plugin_;
    }
    /**
     * <pre>
     *需要更新的插件扩展
     * </pre>
     *
     * <code>optional .core.Plugin plugin = 1;</code>
     */
    public com.akaxin.proto.core.PluginProto.PluginOrBuilder getPluginOrBuilder() {
      return getPlugin();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (plugin_ != null) {
        output.writeMessage(1, getPlugin());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (plugin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlugin());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse other = (com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse) obj;

      boolean result = true;
      result = result && (hasPlugin() == other.hasPlugin());
      if (hasPlugin()) {
        result = result && getPlugin()
            .equals(other.getPlugin());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPlugin()) {
        hash = (37 * hash) + PLUGIN_FIELD_NUMBER;
        hash = (53 * hash) + getPlugin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.HaiPluginProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.HaiPluginProfileResponse)
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.class, com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (pluginBuilder_ == null) {
          plugin_ = null;
        } else {
          plugin_ = null;
          pluginBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.internal_static_site_HaiPluginProfileResponse_descriptor;
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse getDefaultInstanceForType() {
        return com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.getDefaultInstance();
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse build() {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse buildPartial() {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse result = new com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse(this);
        if (pluginBuilder_ == null) {
          result.plugin_ = plugin_;
        } else {
          result.plugin_ = pluginBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse) {
          return mergeFrom((com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse other) {
        if (other == com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse.getDefaultInstance()) return this;
        if (other.hasPlugin()) {
          mergePlugin(other.getPlugin());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.akaxin.proto.core.PluginProto.Plugin plugin_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.proto.core.PluginProto.Plugin, com.akaxin.proto.core.PluginProto.Plugin.Builder, com.akaxin.proto.core.PluginProto.PluginOrBuilder> pluginBuilder_;
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public boolean hasPlugin() {
        return pluginBuilder_ != null || plugin_ != null;
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public com.akaxin.proto.core.PluginProto.Plugin getPlugin() {
        if (pluginBuilder_ == null) {
          return plugin_ == null ? com.akaxin.proto.core.PluginProto.Plugin.getDefaultInstance() : plugin_;
        } else {
          return pluginBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public Builder setPlugin(com.akaxin.proto.core.PluginProto.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plugin_ = value;
          onChanged();
        } else {
          pluginBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public Builder setPlugin(
          com.akaxin.proto.core.PluginProto.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          plugin_ = builderForValue.build();
          onChanged();
        } else {
          pluginBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public Builder mergePlugin(com.akaxin.proto.core.PluginProto.Plugin value) {
        if (pluginBuilder_ == null) {
          if (plugin_ != null) {
            plugin_ =
              com.akaxin.proto.core.PluginProto.Plugin.newBuilder(plugin_).mergeFrom(value).buildPartial();
          } else {
            plugin_ = value;
          }
          onChanged();
        } else {
          pluginBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public Builder clearPlugin() {
        if (pluginBuilder_ == null) {
          plugin_ = null;
          onChanged();
        } else {
          plugin_ = null;
          pluginBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public com.akaxin.proto.core.PluginProto.Plugin.Builder getPluginBuilder() {
        
        onChanged();
        return getPluginFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      public com.akaxin.proto.core.PluginProto.PluginOrBuilder getPluginOrBuilder() {
        if (pluginBuilder_ != null) {
          return pluginBuilder_.getMessageOrBuilder();
        } else {
          return plugin_ == null ?
              com.akaxin.proto.core.PluginProto.Plugin.getDefaultInstance() : plugin_;
        }
      }
      /**
       * <pre>
       *需要更新的插件扩展
       * </pre>
       *
       * <code>optional .core.Plugin plugin = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.proto.core.PluginProto.Plugin, com.akaxin.proto.core.PluginProto.Plugin.Builder, com.akaxin.proto.core.PluginProto.PluginOrBuilder> 
          getPluginFieldBuilder() {
        if (pluginBuilder_ == null) {
          pluginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.akaxin.proto.core.PluginProto.Plugin, com.akaxin.proto.core.PluginProto.Plugin.Builder, com.akaxin.proto.core.PluginProto.PluginOrBuilder>(
                  getPlugin(),
                  getParentForChildren(),
                  isClean());
          plugin_ = null;
        }
        return pluginBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.HaiPluginProfileResponse)
    }

    // @@protoc_insertion_point(class_scope:site.HaiPluginProfileResponse)
    private static final com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse();
    }

    public static com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HaiPluginProfileResponse>
        PARSER = new com.google.protobuf.AbstractParser<HaiPluginProfileResponse>() {
      public HaiPluginProfileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HaiPluginProfileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HaiPluginProfileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HaiPluginProfileResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.plugin.HaiPluginProfileProto.HaiPluginProfileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_HaiPluginProfileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_HaiPluginProfileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_HaiPluginProfileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_HaiPluginProfileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037plugin/hai_plugin_profile.proto\022\004site\032" +
      "\021core/plugin.proto\",\n\027HaiPluginProfileRe" +
      "quest\022\021\n\tplugin_id\030\001 \001(\t\"8\n\030HaiPluginPro" +
      "fileResponse\022\034\n\006plugin\030\001 \001(\0132\014.core.Plug" +
      "in2c\n\027HaiPluginProfileService\022H\n\007profile" +
      "\022\035.site.HaiPluginProfileRequest\032\036.site.H" +
      "aiPluginProfileResponseB0\n\027com.akaxin.pr" +
      "oto.pluginB\025HaiPluginProfileProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akaxin.proto.core.PluginProto.getDescriptor(),
        }, assigner);
    internal_static_site_HaiPluginProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_HaiPluginProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_HaiPluginProfileRequest_descriptor,
        new java.lang.String[] { "PluginId", });
    internal_static_site_HaiPluginProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_HaiPluginProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_HaiPluginProfileResponse_descriptor,
        new java.lang.String[] { "Plugin", });
    com.akaxin.proto.core.PluginProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
